anat:
  query: datatype == 'anat'
  views:
  - three_view(figure='anatThreeView')
  - slice_video(axis=2)

func:
  query: datatype == 'func'
  views:
  - three_view_video
  - carpet_plot
  - mean_std

dwi:
  query: datatype == 'dwi'
  views: 
  - qspace_shells(thresh=10)
  - three_view_video
  - three_view_shell_video
