name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m venv py${{ matrix.python-version }}-venv
          source py${{ matrix.python-version }}-venv/bin/activate
          pip install -U pip
          pip install -e .\[dev,test\]
      - name: Run tests
        id: run-tests
        run: >
          source py${{ matrix.python-version }}-venv/bin/activate
          pytest \
            --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.xml \
            --cov=src tests \
            --log-level=DEBUG \
            --verbose
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "./src"

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - run: |
          python -m venv py3.11-venv
          source py3.11-venv/bin/activate
          pip install -U pip
          pip install -e .\[dev\]
      - name: Run mypy
        run: |
          source py3.11-venv/bin/activate
          mypy ./src --ignore-missing-imports
