name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup python environment
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: pip
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e .\[test\]
      - name: Run tests
        id: run-tests
        run: >
          pytest \
            --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.xml \
            --cov=src tests \
            --log-level=DEBUG \
            -m 'not b2t' \
            -v
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "./src"

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - run: |
          pip install -U pip
          pip install mypy
          mypy ./src --ignore-missing-imports --allow-redefinition
